name : Preparing Zone splitting steps

on:
  push:
    paths:
      - 'zone-splitting-1/**'

jobs:
  Zone_Splitting_Script:
    name: Uploading Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          rm -rf zone-splitting-1/output.txt
          git add .
          git commit -m "Removing output file"
          git push origin main

      - name: running script
        run: sh zone-splitting-1/zone-splitting-1.sh

      - name: commit
        run: |
          git add zone-splitting-1/output.txt
          git commit -m "Final zone splitting output"
          git push origin main
