name : Performing Zoning Steps

on:
  push:
    paths:
      - 'zoneobjectrename/**'

jobs:
  Running_Zoning_Script:
    name: Uploading Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          rm -rf zoneobjectrename/output.txt
          git add .
          git commit -m "Removing output file"
          git push origin main

      - name: running script
        run: sh zoneobjectrename/zoneobjectrename.sh

      - name: commit
        run: |
          git add output.txt
          git commit -m "Final output data"
          git push origin main
