name : Performing Zoning Steps

on:
  push:
    branches: main

jobs:
  Running_Zoning_Script:
    name: Uploading Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: verifying working directory
        run: pwd
      - name: Checking content
        run: ls -l
      - name: running command
        run: cat zoning_info.txt | while IFS=' ' read i j ; do echo -e "alicreate \x22$i\x22, \x22$j\x22" ; done >> output.txt

      - name: View the output file content
        run : cat /home/runner/work/san_script/san_script/output.txt