name : Performing Zoning Steps

on:
  push:
    branches: main

jobs:
  Running_Zoning_Script:
    name: Uploading Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: verifying working directory
        run: pwd
        
      - name: Checking content
        run: ls -l

      - name: running script
        run: sh zoning.sh

      - name: View the output file content
        run : cat /home/runner/work/san_script/san_script/output.txt

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add output.txt
          git commit -m "Final output data"
          git push origin main